project:
  output-dir: "."
  type: website

website:
  title: "Manifold Destiny"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true


