#######################################################################################################################################################
options(scipen=999)
set.seed(1)
library(ManifoldDestinyWASMP)
library(ManifoldDestinyWASMD)
library(dplyr)
library(ggplot2)
library(plotly)
library(htmltools)
library(gridExtra)
library(shiny)
library(DT)
library(kableExtra)
library(htmlTable)
library(usethis)
#debug(lapply(paste0("app",4:4), function(x){recoudatr(mda=md[[x]])}))
#########################################################################################################################################################
md <- ManifoldDestinyWASMD::metad
app1_rp <- selreport(app1,md$app1)
app_1_out <- seloutput(app1_rp)
app2_rp <- selreport(app2,md$app2)
app_2_out <- seloutput(app2_rp)
app3_rp <- selreport(app2,md$app2)
app_3_out <- seloutput(app2_rp)
app4_rp <- selreport(app2,md$app2)
app_4_out <- seloutput(app2_rp)
##########################################################################################################################################################
